apiVersion: v1
kind: Pod
metadata:
  name: read-only-app
spec:
  containers:
  - name: app
    image: nginx
    ports:
    - name: web
      containerPort: 8080
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add:
          - CHOWN
          - DAC_OVERRIDE
          - SETGID
          - SETUID
    volumeMounts:
    - mountPath: /var/tmp/nginx
      name: nginxtmp
  - name: php
    image: fpm
    ports:
    - name: php
      containerPort: 9000
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add:
          - SYS_PTRACE
    volumeMounts:
    - mountPath: /var/
      name: phpcache
    - mountPath: /tmp/
      name: phptmp
  volumes:
  - name: nginxtmp
    emptyDir: {}
  - name: phpcache
    emptyDir: {}
  - name: phptmp
    emptyDir: {}
