apiVersion: v1
kind: Pod
metadata:
  name: read-only-app
spec:
  containers:
  - name: app
    image: nginx
    ports:
    - name: web
      containerPort: 8080
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add:
          - CHOWN
          - DAC_OVERRIDE
          - SETGID
          - SETUID
          - KILL
    resources:
      requests:
        memory: "32Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /var/tmp/nginx
      name: nginxtmp
  - name: php
    image: fpm
    ports:
    - name: php
      containerPort: 9000
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /var/
      name: phpcache
    - mountPath: /tmp/
      name: phptmp
  volumes:
  - name: nginxtmp
    emptyDir: {}
  - name: phpcache
    emptyDir: {}
  - name: phptmp
    emptyDir: {}
